### ISSUE TITLE
Do NOT publish node_modules folder in releases

### ISSUE THREAD

**Issue by unbadfish** [claire-west/svstudio-scripts#2]
The releases should not include the huge `node_modules` folder. 🤣 
In my opinion, the release should be organized into this structure, and throw all js files out.
```
ROOT
|-README.md
|-LICENSE
|-Docs\
| |-index.html
| |-xxx.css
|-Recommended\
|-All-kinds\
| |-hotkey-scripts\
| |-automation\
| |-xyz\
```

**Comment by cv4x** [comment]
This was a mistake when modifying a GitHub workflow. I'll take a look, thanks for the heads-up.

**Comment by unbadfish** [comment]
Thanks for your recognition on this problem. The structure of released files should be as simple and flat as possible.



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 11, 2023 19:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [claire-west/svstudio-scripts] Do NOT publish node_modules folderin releases (Issue #2)




 
This was a mistake when modifying a GitHub workflow. I'll take a look, thanks for the heads-up.

**Comment by cv4x** [comment]
Ah, I tracked down the issue. I was using `grunt-zip` instead of `grunt-contrib-compress`, which evidently has an upward file traversal issue. The extra files were being put in a ".." folder which was completely invisible in Windows file explorer (even after extracting!).

This is what the release package looked like to me:
![image](https://user-images.githubusercontent.com/6045059/231157212-1b6d3ae7-b400-41b9-b2e4-173aa44fb9f2.png)

Of course when I tried unzipping it via the Linux command line suddenly I saw all those extra files you mentioned.

The new release I just pushed has fixed the issue, thanks again for letting me know 👍
